name: Hello World Workflow
on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./action-a
        with:
          who-to-greet: 'GitHub Actions'
